name: Build and Publish Kubebuilder PDF

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          curl -fsSL https://github.com/rust-lang/mdBook/releases/download/v0.4.35/mdbook-v0.4.35-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv mdbook /usr/local/bin/
          cargo install mdbook-pdf

      - name: Modify book.toml to Enable PDF Output
        run: |
          echo "[output.pdf]" >> docs/book.toml

      - name: Build PDF
        run: |
          mdbook build docs

      - name: Move PDF to Docs Directory
        run: |
          mv docs/book/pdf/output.pdf docs/kubebuilder.pdf

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kubebuilder-Book
          path: docs/kubebuilder.pdf

      - name: Commit PDF to Repo (Optional)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/kubebuilder.pdf
          git commit -m "Auto-generated PDF from latest docs"
          git push origin main || echo "No changes to commit"

